<a href="https://colab.research.google.com/github/Cedrik-Black/Data_science/blob/master/exercises/Numpy/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.25.2'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [2]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
np.concatenate((A, B))

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [3]:
np.concatenate((A, B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [4]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
np.concatenate((data, target), axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [6]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [29]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A = np.split(A, [2, 6, 8], axis=1)
A1 = A[0]
A2 = A[1]
A3 = A[2]
A3

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [31]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

32

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [36]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A, axis=1)

array([4, 3, 4, 3, 2, 4, 4, 0, 3, 3])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [48]:
np.set_printoptions(precision=4)
A = np.random.randn(10, 4)
A

array([[-0.9747,  0.7871,  1.1586, -0.8207],
       [ 0.9634,  0.4128,  0.8221,  1.8968],
       [-0.2454, -0.7537, -0.8895, -0.8158],
       [-0.0771,  0.3412,  0.2767,  0.8272],
       [ 0.013 ,  1.4535, -0.2647,  2.7202],
       [ 0.6257, -0.8572, -1.0709,  0.4825],
       [-0.2235,  0.714 ,  0.4732, -0.0728],
       [-0.8468, -1.5148, -0.4465,  0.8564],
       [ 0.2141, -1.2457,  0.1732,  0.3853],
       [-0.8839,  0.1537,  0.0582, -1.143 ]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [51]:
np.set_printoptions(precision=8, suppress=True)
A = np.array([1.2e-6, 1.7e-7])
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [55]:
A = np.random.randn(8, 4)
np.delete(A, 2, 1)

array([[ 0.89959988,  0.30729952,  0.62962884],
       [-0.82899501, -0.56018104,  0.61037027],
       [-0.02090159,  0.11732738, -0.59157139],
       [ 0.54709738, -0.20219265,  1.09877685],
       [ 0.82541635,  0.81350964,  0.02100384],
       [ 0.68195297, -0.31026676, -0.13014305],
       [ 0.09699596,  0.59515703,  2.09238728],
       [-1.00601738, -1.21418861,  0.79166269]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [57]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [60]:
np.set_printoptions(edgeitems=10)
A = np.random.randint(10, size=(100, 30))
A

array([[2, 8, 4, 1, 2, 8, 6, 1, 8, 3, ..., 0, 7, 2, 9, 5, 6, 9, 0, 5, 6],
       [5, 3, 0, 8, 3, 6, 6, 1, 0, 7, ..., 3, 3, 2, 5, 0, 5, 1, 8, 1, 6],
       [0, 6, 4, 7, 3, 9, 6, 5, 4, 3, ..., 3, 3, 2, 6, 8, 4, 3, 1, 1, 4],
       [6, 9, 9, 8, 6, 4, 9, 9, 9, 5, ..., 0, 4, 9, 8, 3, 7, 5, 2, 3, 1],
       [0, 7, 0, 0, 3, 9, 9, 5, 8, 0, ..., 4, 7, 4, 1, 5, 8, 2, 0, 0, 2],
       [9, 4, 2, 8, 7, 2, 8, 5, 6, 3, ..., 6, 8, 0, 1, 2, 2, 7, 6, 5, 9],
       [9, 3, 8, 0, 1, 3, 2, 0, 4, 6, ..., 8, 4, 3, 7, 8, 3, 2, 7, 4, 1],
       [9, 8, 2, 1, 0, 7, 2, 6, 0, 0, ..., 9, 6, 5, 1, 1, 6, 0, 1, 7, 5],
       [1, 6, 3, 1, 5, 8, 8, 7, 2, 2, ..., 5, 6, 3, 7, 8, 0, 6, 8, 9, 4],
       [1, 9, 5, 6, 1, 1, 9, 9, 0, 3, ..., 9, 2, 1, 5, 1, 4, 1, 2, 2, 5],
       ...,
       [9, 8, 3, 2, 9, 0, 9, 5, 6, 9, ..., 1, 9, 7, 9, 8, 0, 6, 7, 2, 3],
       [2, 6, 8, 2, 5, 7, 5, 1, 6, 1, ..., 0, 8, 1, 0, 6, 5, 5, 4, 3, 3],
       [2, 9, 7, 6, 8, 0, 6, 9, 3, 6, ..., 7, 4, 3, 9, 4, 3, 2, 4, 3, 0],
       [2, 9, 9, 7, 6, 1, 